#!/bin/sh
#
# wlan0        Starts WiFi.
#

start() {
        printf "Starting WiFi: "
        ifconfig wlan0 up
        wpa_supplicant -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf -B
        udhcpc -i wlan0 &
        echo "OK"
}
stop() {
        printf "Stopping WiFi: "
        killall udhcpc
        killall wpa_supplicant
	ifconfig wlan0 down
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
