#!/bin/sh
#
# USB        Starts USB Gadget serial.
#

start() {
        printf "Starting USB Gadget serial: "
        modprobe g_serial
        [ $? -eq 0 ] && echo "OK" || echo "ERROR"
}
stop() {
        printf "Stopping USB Gadget serial: "
        modprobe -r g_serial
        # [ $? -eq 0 ] && echo "OK" || echo "ERROR"
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
